In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score


# 1. Load Dataset

df = pd.read_csv("D:/Dataset/car data.csv")   # your file name
print("Dataset Preview:\n")
df.head()

Dataset Preview:

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [2]:
# 2. Data Preprocessing
# Drop Car_Name (not useful)
df.drop("Car_Name", axis=1, inplace=True)

In [3]:
# Convert Year → Age (important feature)
df["Car_Age"] = 2026 - df["Year"]
df.drop("Year", axis=1, inplace=True)

In [4]:
df.head()

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Car_Age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,12

In [5]:
df = pd.get_dummies(df, drop_first=True)

print("\nAfter Encoding:\n")
df.head()

After Encoding:

,Selling_Price,Present_Price,Kms_Driven,Owner,Car_Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,0,1,0,1
1,4.75,9.54,43000,0,13,1,0,0,1
2,7.25,9.85,6900,0,9,0,1,0,1
3,2.85,4.15,5200,0,15,0,1,0,1
4,4.60,6.87,42450,0,12,1,0,0,1

In [6]:
X = df.drop("Selling_Price", axis=1)
y = df["Selling_Price"]

In [7]:
X.head()

,Present_Price,Kms_Driven,Owner,Car_Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,5.59,27000,0,12,0,1,0,1
1,9.54,43000,0,13,1,0,0,1
2,9.85,6900,0,9,0,1,0,1
3,4.15,5200,0,15,0,1,0,1
4,6.87,42450,0,12,1,0,0,1

In [8]:
y.head()

0    3.35
1    4.75
2    7.25
3    2.85
4    4.60
Name: Selling_Price, dtype: float64

In [9]:
#5. Train-Test Split

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [10]:
#6. Train Random Forest Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [11]:
#prediction
y_pred = model.predict(X_test)

In [12]:
 #8. Evaluation
score = r2_score(y_test, y_pred)
print("\nR2 Score:", score)

R2 Score: 0.9608898962659107

In [13]:
new_data = X.iloc[0:5]
predicted_price = model.predict(new_data)

print(predicted_price)

[3.8215 5.051  7.8693 2.6455 4.4785]

In [14]:

# Show Prediction with Message

print("\n------ Car Price Predictions ------\n")

for i in range(len(new_data)):
    print(f"Car {i+1} Details (Input Parameters):")
    print(new_data.iloc[i])  # show features used for prediction
    
    print("Predicted Selling Price:", round(predicted_price[i], 2), "Lakhs")
    print("-----------------------------------")

------ Car Price Predictions ------

Car 1 Details (Input Parameters):
Present_Price                 5.59
Kms_Driven                27000.00
Owner                         0.00
Car_Age                      12.00
Fuel_Type_Diesel              0.00
Fuel_Type_Petrol              1.00
Seller_Type_Individual        0.00
Transmission_Manual           1.00
Name: 0, dtype: float64
Predicted Selling Price: 3.82 Lakhs
-----------------------------------
Car 2 Details (Input Parameters):
Present_Price                 9.54
Kms_Driven                43000.00
Owner                         0.00
Car_Age                      13.00
Fuel_Type_Diesel              1.00
Fuel_Type_Petrol              0.00
Seller_Type_Individual        0.00
Transmission_Manual           1.00
Name: 1, dtype: float64
Predicted Selling Price: 5.05 Lakhs
-----------------------------------
Car 3 Details (Input Parameters):
Present_Price                9.85
Kms_Driven                6900.00
Owner                        0.00
Car_Age                      9.00
Fuel_Type_Diesel             0.00
Fuel_Type_Petrol             1.00
Seller_Type_Individual       0.00
Transmission_Manual          1.00
Name: 2, dtype: float64
Predicted Selling Price: 7.87 Lakhs
-----------------------------------
Car 4 Details (Input Parameters):
Present_Price                4.15
Kms_Driven                5200.00
Owner                        0.00
Car_Age                     15.00
Fuel_Type_Diesel             0.00
Fuel_Type_Petrol             1.00
Seller_Type_Individual       0.00
Transmission_Manual          1.00
Name: 3, dtype: float64
Predicted Selling Price: 2.65 Lakhs
-----------------------------------
Car 5 Details (Input Parameters):
Present_Price                 6.87
Kms_Driven                42450.00
Owner                         0.00
Car_Age                      12.00
Fuel_Type_Diesel              1.00
Fuel_Type_Petrol              0.00
Seller_Type_Individual        0.00
Transmission_Manual           1.00
Name: 4, dtype: float64
Predicted Selling Price: 4.48 Lakhs
-----------------------------------